version: "3"
services:
  app:
    container_name: ojwang-frontend
    image: ojwang-frontend
    stdin_open: true
    build:
      context: .
    ports:
      - '3000:3000'
    volumes:
      - './:/app'
